[package]
name = "order-book"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Christopher Russell"]

[lib]
name = "order_book"

[features]
default = []
tracing = ["dep:tracing", "dep:tracing-subscriber", "order-book-core/tracing"]

[dependencies]
hashbrown = "0.16.1"
log = "0.4.29"
env_logger = "0.11.8"
thiserror = "2.0.18"
num = "0.4.3"
anyhow = "1.0.101"
itertools = "0.14.0"
tracing = { version = "0.1.44", optional = true }
tracing-subscriber = { version = "0.3.22", optional = true }
order-book-derive = { path = "../order_book_derive" }
order-book-core = { path = "../order_book_core" }

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports", "real_blackbox"] }
polars = { version = "0.52.0", features = [
    "polars-io",
    "csv",
    "dtype-array",
], default-features = true }

[[bench]]
name = "book_side"
harness = false

[[bench]]
name = "book_side_tracked"
harness = false

[[bench]]
name = "order_book"
harness = false

[[bench]]
name = "ninja"
harness = false

[[test]]
name = "book_side_tests"

[[test]]
name = "book_side_derive"